version: '4.54'
services:
  playwright-app:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test uiComponenets.spec.ts --project=chromium
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results